package com.abhinav.framework.dto;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class CreateUserResponse {
    private String name;
    private String job;
    private String id;
    private String createdAt;

    // Getters and setters are generated by Lombok
}