import subprocess
import os
from agent.utils.logger import get_logger

logger = get_logger("GitManager")

class GitManager:
    def __init__(self, repo_path: str):
        self.repo_path = repo_path

    def prepare_branch(self, branch_name: str, job_id: str):
        logger.info(f"Preparing branch: {branch_name}", job_id=job_id)
        subprocess.run(["git", "checkout", "main"], cwd=self.repo_path)
        subprocess.run(["git", "pull", "origin", "main"], cwd=self.repo_path)
        # Use -B to overwrite branch if it exists locally
        subprocess.run(["git", "checkout", "-B", branch_name], cwd=self.repo_path)

    def commit_and_push(self, branch_name: str, message: str, job_id: str) -> Optional[str]:
        subprocess.run(["git", "add", "."], cwd=self.repo_path)
        subprocess.run(["git", "commit", "-m", message], cwd=self.repo_path)
        subprocess.run(["git", "push", "origin", branch_name, "--force"], cwd=self.repo_path)
        
        # Create PR using gh CLI
        try:
            res = subprocess.run(["gh", "pr", "create", "--title", message, "--body", "Generated by Agent.", "--head", branch_name], 
                               cwd=self.repo_path, capture_output=True, text=True)
            if res.returncode == 0:
                pr_link = res.stdout.strip()
                logger.info(f"PR Created: {pr_link}", job_id=job_id)
                return pr_link
            return None
        except Exception as e:
            logger.error(f"PR creation failed: {e}", job_id=job_id)
            return None
