import time
from typing import Optional, List
from agent.utils.logger import get_logger
from agent.core.state_manager import StateManager, JobState
from agent.providers.gemini_generator import GeminiGenerator, GeneratedFile

logger = get_logger("RuleEngine")

class RuleEngine:
    def __init__(self):
        self.state_manager = StateManager()
        self.generator = GeminiGenerator()

    def execute(self, job_id: str, yaml_path: str, is_dryrun: bool) -> Optional[List[GeneratedFile]]:
        logger.info(f"Rule Engine starting for trigger: {yaml_path}", job_id=job_id)
        try:
            with open(yaml_path, 'r') as f:
                yaml_content = f.read()
        except FileNotFoundError:
            self.state_manager.update_state(job_id, JobState.FAILED, error_message="YAML missing")
            return None
        start_time = time.time()
        generated_files = self.generator.generate_code(job_id, yaml_content)
        if not generated_files:
            self.state_manager.update_state(job_id, JobState.FAILED, error_message="LLM Generation Failed")
            return None
        if is_dryrun:
            self.state_manager.update_state(job_id, JobState.COMPLETED)
            return generated_files
        self.state_manager.update_state(job_id, JobState.CODE_GENERATED)
        from agent.core.guardrails import SecurityGuardrails
        if not SecurityGuardrails.validate_generated_files(generated_files, job_id):
            self.state_manager.update_state(job_id, JobState.FAILED, error_message="Guardrails failed.")
            return None
        self.validate_and_commit(job_id, generated_files, yaml_content, start_time)
        return generated_files

    def validate_and_commit(self, job_id: str, files: List[GeneratedFile], original_yaml: str, start_time: float):
        from agent.core.git_manager import GitManager
        from agent.worker.docker_runner import DockerRunner
        from agent.core.healing_strategy import AdaptiveHealingStrategy
        from agent.core.guardrails import SecurityGuardrails
        git = GitManager()
        docker = DockerRunner()
        healer = AdaptiveHealingStrategy()
        job_info = self.state_manager.get_job(job_id) or {}
        api_name = job_info.get("api_name") or "api-automation"
        branch_name = git.prepare_branch(api_name, job_id)
        git.write_files(files, job_id)
        max_retries = 2
        success = False
        error_logs = ""
        current_files = files
        for attempt in range(max_retries + 1):
            if not SecurityGuardrails.enforce_execution_limits(attempt, max_retries, start_time, 180, job_id):
                break
            if attempt > 0:
                self.state_manager.increment_retry(job_id)
                current_files = healer.attempt_heal(job_id, attempt, error_logs, original_yaml, current_files)
                if not current_files or not SecurityGuardrails.validate_generated_files(current_files, job_id):
                    break
                git.write_files(current_files, job_id)
            self.state_manager.update_state(job_id, JobState.VALIDATING)
            result_ok, logs = docker.execute_validation(job_id, attempt + 1)
            if result_ok:
                success = True
                break
            else:
                self.state_manager.update_state(job_id, JobState.FAILED_VALIDATION, error_message=logs[-1000:])
                error_logs = logs
        if success:
            git.commit_and_push(branch_name, f"🤖 Automated API generation for {api_name}", job_id)
            pr_link = git.create_pr(branch_name, f"Automated tests for {api_name}", "Generated by Agent.", job_id)
            self.state_manager.update_state(job_id, JobState.PR_CREATED, pr_link=pr_link)
            logger.info(f"== TELEGRAM ==\n✅ PR Created: {pr_link}", job_id=job_id)
        else:
            self.state_manager.update_state(job_id, JobState.FAILED, error_message="Tests failed after healing.")
            logger.info(f"== TELEGRAM ==\n❌ Build Failed", job_id=job_id)
